yarnPath: .yarn/releases/yarn-3.3.0.cjs
nodeLinker: node-modules

# https://github.com/facebook/create-react-app/issues/10463#issuecomment-1022751568
packageExtensions:
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"